  name: Get TVL       
  on:
    schedule:
      - cron:  '30 6,18 * * *'
  jobs:
    refresh:
      runs-on: ubuntu-latest
      steps:
        - name: Fetch Data to File
          uses: gautemo/fetch-api-data-action@1.1.0
          with:
            url: 'http://101.34.208.17/data'    
        - name: Build and Deploy
          uses: JamesIves/github-pages-deploy-action@releases/v3
          with:
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            BRANCH: gh-pages
            FOLDER: actions # The location of the data.json file saved by the Fetch API Data action.
            TARGET_FOLDER: data # Saves the data into the 'data' directory on the master branch.